// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJmFk36YPiVtKph2zQiV1JqArYRUq84mk',
    appId: '1:607469818084:web:6f06786a851f15eb751cf1',
    messagingSenderId: '607469818084',
    projectId: 'quizzgame-4b7de',
    authDomain: 'quizzgame-4b7de.firebaseapp.com',
    databaseURL: 'https://quizzgame-4b7de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizzgame-4b7de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIerc-ex8n_wLmBhSKdGhU3FoVZ1onXKg',
    appId: '1:607469818084:android:6d0a08a096dfc2fd751cf1',
    messagingSenderId: '607469818084',
    projectId: 'quizzgame-4b7de',
    databaseURL: 'https://quizzgame-4b7de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizzgame-4b7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGYeJG63RIa9nT5gPmr9pz7d1tP4nrMps',
    appId: '1:607469818084:ios:f2d8c6bba3d8d665751cf1',
    messagingSenderId: '607469818084',
    projectId: 'quizzgame-4b7de',
    databaseURL: 'https://quizzgame-4b7de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizzgame-4b7de.firebasestorage.app',
    iosBundleId: 'com.example.quizzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGYeJG63RIa9nT5gPmr9pz7d1tP4nrMps',
    appId: '1:607469818084:ios:f2d8c6bba3d8d665751cf1',
    messagingSenderId: '607469818084',
    projectId: 'quizzgame-4b7de',
    databaseURL: 'https://quizzgame-4b7de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizzgame-4b7de.firebasestorage.app',
    iosBundleId: 'com.example.quizzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJmFk36YPiVtKph2zQiV1JqArYRUq84mk',
    appId: '1:607469818084:web:3cb6f038de767cdd751cf1',
    messagingSenderId: '607469818084',
    projectId: 'quizzgame-4b7de',
    authDomain: 'quizzgame-4b7de.firebaseapp.com',
    databaseURL: 'https://quizzgame-4b7de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quizzgame-4b7de.firebasestorage.app',
  );

}